- .eslintrc.js
- components.json
- package-lock.json
- package.json
- src/components/ui/alert-dialog.tsx
- src/components/ui/avatar.tsx
- src/components/ui/badge.tsx
- src/components/ui/button.tsx
- src/components/ui/card.tsx
- src/components/ui/dropdown-menu.tsx
- src/components/ui/form.tsx
- src/components/ui/input.tsx
- src/components/ui/label.tsx
- src/components/ui/radio-group.tsx
- src/components/ui/switch.tsx
- src/components/ui/textarea.tsx
- src/components/ui/toast.tsx
- src/components/ui/toaster.tsx
- src/components/ui/use-toast.ts
- src/lib/utils.ts
- tailwind.config.ts
없음
shadcn ui 추가하였습니다.
- alert-dialog
- avatar
- badge
- button
- card
- dropdown-menu
- form
- input
- label
- radio-group
- switch
- textarea
- toast
> :lipstick: shadcn ui setup

- public/meatballIcon.svg
- src/apis/epigram.ts
- src/apis/user.ts
- src/components/epigram/MoreOptionMenu.tsx
- src/lib/constants.ts
- src/pageLayout/Epigram/EpigramFigure.tsx
- src/pages/epigram/[id].tsx
- src/types/epigram.types.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-43)
에피그램조회에서 받은 writerId와 유저정보에서의 Id를 비교해 같으면 미트볼 아이콘 표시
미트볼 아이콘에서는 에피그램 수정, 삭제 표시(기능은 아직 X)
> FE-43✨ 사용자 ID에 따른 미트볼아이콘 표시

- src/pages/index.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-24)
소개 페이지애서 로그인 페이지로 이동 구현
해당 epic에 로그인 페이지가 없기 때문에 아직 404임
> FE-24 :sparkles: 소개 페이지 이동 구현

- src/pages/auth/SignUp.tsx
- src/schema/auth.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-68)
- 로그인 페이지 react-hook-form + zod를 사용하여 이메일, 비밀번호, 비밀번호 확인, 닉네임 입력창에 대한 유효성 검사
아무 값도 입력하지 않았을 때
유효하지 않은 값을 입력했을 때
유효한 값 입력했을 때
> FE-68 :sparkles: 회원가입 페이지 유효성 검사

- src/pageLayout/Epigram/AddEpigram.tsx
- src/pages/epigram/add.tsx
[Ticket](https://trello.com/)
글 작성 페이지 UI 추가했습니다!
PC
Mobile.Tablet
> 💄 글작성 페이지 UI추가

- package-lock.json
- package.json
- src/components/search/RecentSearches.tsx
- src/components/search/SearchBar.tsx
- src/pageLayout/SearchLayout/SearchLayout.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-65?atlOrigin=eyJpIjoiMmVjYWE2MjE3YjA1NDE3MGI5M2JmYzBmYTAzYWUyMzkiLCJwIjoiaiJ9)
검색 페이지 최근 검색어 기능입니다.
검색어를 입력하여 제출하면 로컬 스토리지에 저장되고 최근 검색어 컴포넌트에 나타나게됩니다.
최근 순서대로 왼쪽부터 추가되며 최근 검색어 클릭 시 클릭 된 검색어로 검색됩니다. (이후 연동 필요)
중복되는 검색어는 기존의 검색어를 제일 앞으로 보냅니다. 최대 10개로 제한합니다.
++ 멘토링때 디바운스를 말씀해주셔서 사용해보려 했는데 잘 안되서 그냥 삭제했습니다...!
> FE-65  ✨최근 검색어 기능

- next.config.mjs
- package-lock.json
- package.json
- src/apis/index.ts
- src/apis/user.ts
- src/components/ui/dialog.tsx
- src/hooks/userQueryHooks.ts
- src/pageLayout/MypageLayout/MyPageLayout.tsx
- src/pages/_app.tsx
- src/pages/mypage/index.tsx
- src/schema/user.ts
- src/types/user.ts
- src/user/ui-profile/Profile.tsx
- src/user/ui-profile/ProfileEdit.tsx
- src/user/utill/constants.ts
- src/user/utill/fileNameChange.ts
- tailwind.config.js
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-34?atlOrigin=eyJpIjoiYmE1N2M4MDQwMDZhNDMwN2E5N2M2Nzg2NDYzYTQ0YTYiLCJwIjoiaiJ9)
마이페이지 프로필 수정 기능
- 프로필 사진 변경
- 닉네임 변경 (피그마 시안에는 프로필 사진만 변경 가능하도록 되어있었지만 모달창을 추가하여 닉네임도 변경할 수 있도록 수정)
:memo: formik(폼 라이브러리) / yup(유효성검사) / shadcn/ui dialog 설치
> FE-34 :sparkles: 마이페이지 프로필 수정 기능

- src/apis/add.ts
- src/apis/index.ts
- src/hooks/epigramQueryHook.ts
- src/pageLayout/Epigram/AddEpigram.tsx
- src/pages/epigram/[id].tsx
- src/schema/addEpigram.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-72)
1. 에피그램 등록(/epigram, POST) api 연동
2. 에피그램 등록되면 등록된 에피그램 상세 페이지로 이동
폼 제출 성공
폼 제출 실패
> FE-72 ✨ 에피그램 등록 api연동

- package-lock.json
- package.json
- public/icon/arrow-bottom-icon.svg
- public/icon/arrow-right-icon.svg
- src/hooks/useCalendar.ts
- src/pageLayout/MypageLayout/MyPageLayout.tsx
- src/user/ui-profile/Calendar.tsx
- src/user/utill/constants.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-36?atlOrigin=eyJpIjoiNmE2NzcwYjE4ZDFhNDgwMWI1MzJjYThjODBkMzRhZGQiLCJwIjoiaiJ9)
- 마이페이지 감정달력 UI 작업
- 마이페이지 감정달력 캘린더 출력 함수
- date-fns 라이브러리 설치
- useCalendar hook 추가 (캘린더 날짜 계산하는 hook)
- 한 달이 6주인 경우
- 한 달이 5주인 경우
> FE-36 :sparkles: 마이페이지 캘린더 출력 함수

- src/apis/epigram.ts
- src/apis/index.ts
- src/apis/queries.ts
- src/components/epigram/DeleteAlertModal.tsx
- src/components/epigram/MoreOptionMenu.tsx
- src/hooks/useDeleteEpigramHook.ts
- src/pageLayout/Epigram/EpigramFigure.tsx
- src/pages/_app.tsx
- src/types/epigram.types.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-45)
상세페이지 에피그램 삭제 api연동
삭제를 눌렀을때 확인 모달 컴포넌트 생성
삭제 눌렀을 
삭제하기 눌렀을 때,
> FE-45✨ 에피그램 삭제 api 연동

- src/apis/epigramComment.ts
- src/hooks/useDeleteCommentHook.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-57?atlOrigin=eyJpIjoiOTk4ZmI0NjNhODBiNDE0OThiMzc5N2FkNDk2NjdhMGMiLCJwIjoiaiJ9)
댓글 삭제 API
> FE-57 :sparkles: 댓글 삭제 API

- src/hooks/useCalendar.ts
- src/pageLayout/MypageLayout/MyPageLayout.tsx
- src/types/emotion.ts
- src/user/ui-profile/Calendar.tsx
- src/user/ui-profile/CalendarHeader.tsx
- src/user/ui-profile/Chart.tsx
- src/user/ui-profile/EmotionMonthlyLogs.tsx
- src/user/utill/constants.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-37?atlOrigin=eyJpIjoiNGM0OGRiMWIwY2I3NGFjZGE3MzBjNmNlYWVlYTM0NDciLCJwIjoiaiJ9)
감정 달력에서 선택 한 '월' 기준 감정 로그를 차트로 구현.
- 라이브러리 없이 svg로 구현
> FE-37 :sparkles: 마이페이지 감정차트

- src/apis/add.ts
- src/apis/index.ts
- src/hooks/epigramQueryHook.ts
- src/hooks/useTagManagementHook.ts
- src/pageLayout/Epigram/AddEpigram.tsx
- src/pages/addEpigram.tsx
- src/schema/addEpigram.ts
> FE-29 :twisted_rightwards_arrows: epic 브랜치 최신화

- src/apis/oauth.ts
- src/hooks/useKakaoLogin.ts
- src/pages/auth/SignIn.tsx
- src/pages/auth/redirect/kakao/index.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-70)
네이버, 구글, 카카오 간편 로그인 작업
네이버 간편 로그인
구글 간편 로그인
카카오톡 간편 로그인
> FE-70 :sparkles: 간편 로그인 설정

- src/apis/auth.ts
- src/hooks/useSignInMutation.ts
- src/pages/auth/SignIn.tsx
- src/schema/auth.ts
> FE-51 :twisted_rightwards_arrows: 공용 API 최신화 (충돌수정)

- src/hooks/userQueryHooks.ts
> FE-27 :twisted_rightwards_arrows: 마이페이지 최신화

- src/apis/postEmotion.ts
- src/schema/emotion.ts
- src/utils/emotionMap.ts
없음
감정 영어 이름 수정
postEmotion 함수의 토큰 전달 부분 제거(Header에 토큰 전달 부분 포함)
> FE-51 🔨 오늘의 감정 관련 수정

- src/apis/epigramComment.ts
- src/apis/queries.ts
- src/apis/user.ts
- src/hooks/useCommentsHook.ts
- src/hooks/useGetMyContentHook.ts
- src/pageLayout/MypageLayout/MyContent.tsx
- src/pageLayout/MypageLayout/MyPageLayout.tsx
- src/schema/user.ts
- src/user/ui-content/MyComment.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-39?atlOrigin=eyJpIjoiYzQ3MDhjNjQyZjVjNDcwZmFhMTI1MDJkNjQ0YTA4ODAiLCJwIjoiaiJ9)
> FE-27 :sparkles: 마이페이지 내 댓글목록 조회

- src/apis/postGoogleOauth.ts
- src/apis/postNaverOauth.ts
- src/hooks/useGoogleLogin.ts
- src/hooks/useKakaoLogin.ts
- src/hooks/useNaverLogin.ts
- src/pages/auth/SignIn.tsx
- src/pages/auth/redirect/google-callback/index.ts
- src/pages/auth/redirect/naver/index.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-29)
로그인 페이지에 관한 이동 경로 수정 및 간편 로그인 수정
> FE-29 :wrench: 로그인 페이지 수정

- src/hooks/useSignInMutation.ts
티켓 없음
로그인 뮤테이션 훅 수정
- onSuccess일 때 라우팅 수정
- onError 에러로직 수정
> FE-29 :wrench: 로그인 뮤테이션 훅 수정

- public/spinner.svg
- src/apis/getRecentEpigrams.ts
- src/components/main/RecentEpigram.tsx
- src/hooks/useGetRecentEpigrams.ts
- src/schema/recentEpigram.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-17)
최신 에피그램 조회에 'cursor' 파라미터 추가
최신 에피그램 더보기 버튼 클릭 시 화면 깜빡임 없애기 위해 스피너 추가
> FE-17 :bug: 최신 에피그램 더보기 조회 기능 수정

- public/spinner.svg
- src/apis/getRecentComments.ts
- src/components/Card/CommentCard.tsx
- src/components/main/RecentComment.tsx
- src/hooks/useGetRecentComments.ts
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-18/)
최신 댓글 조회에 'cursor' 파라미터 추가
최신 댓글 더보기 버튼 클릭 시 화면 깜빡임 없애기 위해 스피너 추가
댓글 사용자 프로필 사진 출력 구현 / 프로필 이미지가 null인 경우 테스트 이미지 출력
> FE-18 :bug: 최신 댓글 더보기 조회 기능 수정

- src/components/Emotion/EmotionSelector.tsx
- src/components/main/TodayEmotion.tsx
- src/components/ui/toast.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-16)
오늘의 감정을 선택하면 1초 후 컴포넌트가 사라지는 기능 구현
감정 선택 취소 시 토스트 뜨는 오류 수정 / 새로고침 시 선택한 감정을 출력
토스트 배경색 흰색으로 수정
> FE-16 :bug: 오늘의 감정 저장 기능 수정

- src/components/main/TodayEmotion.tsx
- src/pageLayout/MypageLayout/MyPageLayout.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-35?atlOrigin=eyJpIjoiMDNkMDk5ZGYxMzA4NDAyZWI2M2FiYmZkMGVlMzU2N2EiLCJwIjoiaiJ9)
마이페이지 오늘의 감정 선택 컴포넌트 연동
> FE-35 :sparkles: 마이페이지 오늘의 감정 컴포넌트 연동

- public/icon/grid-icon.svg
- public/icon/sort-icon.svg
- src/components/main/FAB.tsx
- src/pageLayout/Feed/AddEpigramFAB.tsx
- src/pageLayout/Feed/EpigramFeed.tsx
- src/pageLayout/Feed/FeedCard.tsx
- src/pageLayout/Feed/FeedPageLayout.tsx
- src/pageLayout/Feed/MoreEpigramButton.tsx
- src/pages/feed/index.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-83)
> FE-83 ✨ 피드 페이지 구현

- src/pageLayout/MypageLayout/MyContent.tsx
마이페이지 내 에피그램/댓글 선택을 <Button> 컴포넌트로 변경
> FE-35 :recycle: 마이페이지 내 에피그램/댓글 선택 버튼컴포넌트로 변경

- src/apis/queries.ts
- src/hooks/useEpigramCommentsQueryHook.ts
- src/hooks/usePatchCommentHook.ts
- src/hooks/usePostCommentHook.ts
- src/pageLayout/Epigram/EpigramFigure.tsx
> FE-54🐛 댓글 불러오지못하는  문제 해결

- next.config.mjs
- src/apis/index.ts
- src/apis/postGoogleOauth.ts
- src/apis/queries.ts
- src/hooks/useGoogleLogin.ts
- src/hooks/useSignInMutation.ts
- src/pages/auth/SignIn.tsx
- src/pages/auth/callback/google/index.ts
- src/pages/mypage/index.tsx
> FE-27 :twisted_rightwards_arrows: 마이페이지 브랜치 최신화

- package-lock.json
- package.json
- src/components/mypage/Chart.tsx
- src/pages/mypage/index.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-85?atlOrigin=eyJpIjoiZGQ5ODYwYThlNzVmNGE5Y2E3OWE0M2JhZjk3YTM1YmYiLCJwIjoiaiJ9)
감정 차트 recharts 라이브러리를 이용하여 구현
> FE-85 :recycle: 마이페이지 감정차트 리팩토링

- src/components/main/FAB.tsx
- src/pageLayout/About/AboutPageLayout.tsx
- src/pageLayout/Epigrams/MainLayout.tsx
- src/pageLayout/Feed/AddEpigramFAB.tsx
> FE-48 :lipstick: ui 수정

- src/components/Card/UserProfileModal.tsx
- src/components/epigram/Comment/CommentItem.tsx
- src/components/ui/dialog_dim.tsx
- src/pageLayout/Epigram/EpigramFigure.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-77)
- 태그 클릭 시 해당 키워드 검색페이지로 이동
- 댓글 프로필 클릭 시 프로필 모달 추가
> FE-77✨ 댓글 프로필 모달 추가

- package-lock.json
- package.json
- src/components/Card/UserProfileModal.tsx
- src/components/epigram/Comment/CommentItem.tsx
- src/components/main/FAB.tsx
- src/components/mypage/Chart.tsx
- src/components/ui/dialog_dim.tsx
- src/hooks/useDeleteCommentHook.ts
- src/hooks/useEpigramCommentsQueryHook.ts
- src/pageLayout/About/AboutPageLayout.tsx
- src/pageLayout/Epigram/EpigramFigure.tsx
- src/pageLayout/Epigrams/MainLayout.tsx
- src/pageLayout/Feed/AddEpigramFAB.tsx
- src/pageLayout/MypageLayout/MyContent.tsx
- src/pages/mypage/index.tsx
> FE-29 :twisted_rightwards_arrows: 브랜치 최신화

- src/apis/user.ts
- src/components/epigram/Comment/CommentItem.tsx
- src/components/mypage/MyComment.tsx
- src/hooks/useCommentsHook.ts
- src/hooks/useDeleteCommentHook.ts
- src/pageLayout/MypageLayout/MyContent.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-86?atlOrigin=eyJpIjoiY2E0Y2E4YWUzZDZlNDk0MDhhN2YwYjI1ZTMwZDllYWUiLCJwIjoiaiJ9)
1. ' 내 에피그램 및 댓글' 수정/삭제 후 재조회
2. 비밀 댓글 자물쇠 아이콘 추가
> FE-86 :recycle: 마이페이지 내 댓글목록 조회 코드 리팩토링

- src/apis/auth.ts
- src/hooks/useRefreshToken.ts
- src/pages/auth/SignIn.tsx
- src/pages/auth/SignUp.tsx
- src/schema/auth.ts
> FE-27 :twisted_rightwards_arrows: 마이페이지 브랜치 최신화

- src/components/Header/NewHeader.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-87?atlOrigin=eyJpIjoiYTk2OTQxMGM0OTdhNDYwOTk2MWU3ZWM2NTU1YTM1MDEiLCJwIjoiaiJ9)
헤더에 로그아웃 버튼 추가
> FE-27 :sparkles: 로그아웃 버튼 추가

- src/pageLayout/MypageLayout/MyContent.tsx
> FE-27 :bug: prettier 에러 수정

- public/spinner.svg
- src/components/main/FAB.tsx
- src/components/main/RecentComment.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-88)
icon 사이즈 full로 들어가 있어서 중앙정렬 되어있습니다. 배경색은 피그마에서 지정해준대로 했는데 다르게 보여서 아예 없앴습니다.
스피더 아이콘 자체에 배경색이 흰색으로 들어 있었는데 아이콘 코드를 수정해서 배경색을 없앴습니다.  
> FE-88 💄 피드백 반영한 ui 수정

- src/components/mypage/Calendar.tsx
- src/components/mypage/Chart.tsx
- src/components/mypage/Profile.tsx
- src/hooks/useMyContentState.tsx
- src/pageLayout/MypageLayout/MyContent.tsx
- src/pageLayout/MypageLayout/MyPageLayout.tsx
- src/pages/mypage/index.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-89?atlOrigin=eyJpIjoiOTkzNjE3ZjdiOTA4NGVkZDkwN2E4ODg5NWM0MDQxODQiLCJwIjoiaiJ9)
- 상태관리 훅 분리
- 내 에피그램 목록 중복데이터 필터링
> FE-89 :recycle: 마이페이지 내 에피그램 목록조회 리팩토링

- src/components/main/RecentComment.tsx
- src/components/main/RecentEpigram.tsx
- src/pages/mypage/index.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-91?atlOrigin=eyJpIjoiOThhNjBjZmVhYWQ2NGM2N2I2ZmJiMjVlMjUyMzQ2OWYiLCJwIjoiaiJ9)
최신 에피그램 목록 및 댓글 중복으로 출력되는 오류 수정
> FE-91 :bug: 메인페이지 에피그램 및 댓글목록 중복오류 수정

- src/pageLayout/Feed/EpigramFeed.tsx
[Ticket](https://codeitsprint5.atlassian.net/browse/FE-94)
[피드 페이지] 목록 중복 오류 수정
> FE-82 :wrench: 피드페이지 오류 수정

- package-lock.json
- src/components/main/RecentComment.tsx
- src/components/main/RecentEpigram.tsx
- src/pageLayout/Feed/EpigramFeed.tsx
> FE-27 :twisted_rightwards_arrows: 브랜치 최신화
